apiVersion: v2
name: kibana
description: Kibana data visualization and exploration for Elasticsearch
type: application
version: 0.1.0
appVersion: "8.11.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/cywf/helm-charts
sources:
  - https://github.com/cywf/helm-charts
  - https://github.com/elastic/kibana
maintainers:
  - name: cywf
    url: https://github.com/cywf
keywords:
  - elasticsearch
  - kibana
  - logging
  - visualization
  - observability
