apiVersion: v2
name: elastalert
description: ElastAlert alerting for Elasticsearch
type: application
version: 0.1.0
appVersion: "2.14.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/cywf/helm-charts
sources:
  - https://github.com/cywf/helm-charts
  - https://github.com/jertel/elastalert2
maintainers:
  - name: cywf
    url: https://github.com/cywf
keywords:
  - elastalert
  - elasticsearch
  - alerting
  - monitoring
