# Chart.yaml
apiVersion: v2
name: docker
version: 0.1.0
description: A Helm chart for deploying Docker with a pre-configured network using Zerotier.

dependencies:
  - name: zerotier
    version: 0.1.0
    repository: https://charts.zerotier.com/
