apiVersion: v2
name: strelka
description: Strelka file scanning system
type: application
version: 0.1.0
appVersion: "0.24.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/cywf/helm-charts
sources:
  - https://github.com/cywf/helm-charts
  - https://github.com/target/strelka
maintainers:
  - name: cywf
    url: https://github.com/cywf
keywords:
  - strelka
  - security
  - file-scanning
  - malware-analysis
