apiVersion: v2
name: zerotier
description: ZeroTier software-defined networking on Kubernetes
type: application
version: 0.1.0
appVersion: "latest"
kubeVersion: ">=1.28.0-0"
home: https://github.com/cywf/helm-charts
sources:
  - https://github.com/cywf/helm-charts
  - https://github.com/zerotier/ZeroTierOne
maintainers:
  - name: cywf
    url: https://github.com/cywf
keywords:
  - networking
  - vpn
  - zerotier
  - sdn
