# This Helm chart will deploy the latest version of the ZeroTier Docker image and set up a single replica deployment. You'll need to specify the network ID and network access token for your ZeroTier network by editing the values in the env section. This Helm chart also sets up a service to expose the ZeroTier API on port 9993. You can specify your own node selector and tolerations as well.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerotier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerotier
  template:
    metadata:
      labels:
        app: zerotier
    spec:
      containers:
        - name: zerotier
          image: zerotier/zerotier-one:latest
          securityContext:
            privileged: true
          env:
            - name: ZT_NC_AUTO_CREATE
              value: "1"
            - name: ZT_NC_NETWORK
              value: "<INSERT YOUR NETWORK ID HERE>"
            - name: ZT_NC_TOKEN
              value: "<INSERT YOUR NETWORK ACCESS TOKEN HERE>"
          volumeMounts:
            - name: ztsocket
              mountPath: /var/lib/zerotier-one
          ports:
            - containerPort: 9993
              name: zerotier-api
              protocol: TCP
      volumes:
        - name: ztsocket
          hostPath:
            path: /var/lib/zerotier-one
      nodeSelector: <INSERT YOUR NODE SELECTOR HERE>
      tolerations:
        - key: <INSERT YOUR TOLERATIONS HERE>
          operator: "Equal"
          value: <INSERT YOUR TOLERATIONS VALUE HERE>
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: zerotier
  labels:
    app: zerotier
spec:
  type: ClusterIP
  ports:
    - name: zerotier-api
      port: 9993
      targetPort: 9993
  selector:
    app: zerotier
