{{- if .Values.zerotier.accessToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zerotier.fullname" . }}
  labels:
    {{- include "zerotier.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-token: {{ .Values.zerotier.accessToken | quote }}
{{- end }}
