apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch.fullname" . }}
  labels:
    app: {{ include "elasticsearch.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "elasticsearch.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "elasticsearch.name" . }}
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          env:
            - name: cluster.name
              value: elasticsearch
            - name: node.name
              value: "{{ include "elasticsearch.fullname" . }}-node"
            - name: discovery.seed_hosts
              value: "{{ include "elasticsearch.fullname" . }}-discovery"
            - name: cluster.initial_master_nodes
              value: "{{ include "elasticsearch.fullname" . }}-node"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          readinessProbe:
            httpGet:
              path: /_cat/indices
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      initContainers:
        - name: init-sys
