apiVersion: v2
name: redis
description: Redis in-memory data store
type: application
version: 0.1.0
appVersion: "7.2.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/cywf/helm-charts
sources:
  - https://github.com/cywf/helm-charts
  - https://github.com/redis/redis
maintainers:
  - name: cywf
    url: https://github.com/cywf
keywords:
  - redis
  - database
  - cache
  - key-value
